# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_solve <- function(lambda_c, lambda_a, mu, gamma, chosen_interval, inte_method, init_states, time, atol, rtol) {
    .Call(`_DAISIEde_cpp_solve`, lambda_c, lambda_a, mu, gamma, chosen_interval, inte_method, init_states, time, atol, rtol)
}

